repos:
  - repo: https://github.com/psf/black
    rev: 25.1.0  # Update this to the latest version
    hooks:
      - id: black

  - repo: https://github.com/pycqa/flake8
    rev: 7.2.0  # Update this to the latest version
    hooks:
      - id: flake8

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.15.0
    hooks:
      - id: mypy
        entry: mypy src/
        args: ["--config-file=mypy.ini", "--no-incremental"]
        additional_dependencies: [PyQt5-stubs]
        pass_filenames: false  # ✅ This is the KEY to prevent pre-commit from passing individual file paths

  - repo: https://github.com/PyCQA/bandit
    rev: 1.8.3  # Update this to the latest version
    hooks:
      - id: bandit
        args: ['--skip', 'B101']

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0  # Update this to the latest version
    hooks:
      - id: check-json
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
