name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: write

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Run unit tests
        run: pytest tests/
        env:
          QT_QPA_PLATFORM: offscreen
          IDW_TEST_MODE: "1"

  lint:
    name: Code Linting & Security Checks
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 black mypy bandit

      - name: Run flake8 (Linting)
        run: flake8 src/

      - name: Run Black (Code Formatting Check)
        run: black --check src/

      - name: Run mypy (Type Checking)
        run: mypy --config-file mypy.ini src/

      - name: Check for Outdated Dependencies
        run: |
          pip list --outdated

      - name: Run Bandit (Security Check)
        run: |
          timeout 120s bandit -r . \
            --exclude ./tests,./docs,./config_profiles

  package:
    name: Package Application
    runs-on: ubuntu-latest
    needs: [test, lint]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pip-tools
          pip-compile requirements.in
          pip install -r requirements.txt

      - name: Build Executable
        run: |
          python -m PyInstaller --onefile --name interactive-data src/main.py

      - name: Upload Executable as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: interactive-data-executable
          path: dist/interactive-data

  release:
    name: Create GitHub Release
    runs-on: ubuntu-latest
    needs: [package]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: interactive-data-executable
          path: dist/

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: dist/interactive-data
          tag_name: v1.0.${{ github.run_number }}
          name: "Release v1.0.${{ github.run_number }}"
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
